---
- name: create blackbox_exporter system group
  group:
    name: blackbox-exp
    system: yes
    state: present

- name: create blackbox_exporter system user
  user:
    name: blackbox-exp
    system: yes
    shell: "/sbin/nologin"
    group: blackbox-exp
    createhome: no

- name: create blackbox_exporter directories
  file:
    path: "{{ item }}"
    state: directory
    owner: blackbox-exp
    group: blackbox-exp
    mode: 0755
  with_items:
    - "{{ blackbox_exporter_root_dir }}"
    - "{{ blackbox_exporter_log_dir }}"

- name: download blackbox exporter binary to local folder
  become: no
  unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64/blackbox_exporter"
  run_once: true
  delegate_to: localhost

- name: propagate blackbox exporter binary
  copy:
    src: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-amd64/blackbox_exporter"
    dest: "/opt/blackbox_exporter"
    mode: 0755
    owner: blackbox-exp
    group: blackbox-exp
  notify:
    - restart blackbox exporter

- name: create systemd service unit
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart blackbox exporter

- name: configure blackbox exporter
  template:
    src: blackbox_exporter.yml.j2
    dest: /etc/blackbox_exporter.yml
    owner: blackbox-exp
    group: blackbox-exp
    mode: 0644
  notify:
    - reload blackbox exporter

- name: ensure blackbox_exporter service is enabled
  service:
    name: blackbox_exporter
    enabled: yes
