---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart blackbox exporter
  service:
    name: blackbox_exporter
    state: restarted

- name: reload blackbox exporter
  service:
    name: blackbox_exporter
    state: reloaded
