---
- name: restart blackbox exporter
  systemd:
    daemon_reload: yes
    name: blackbox_exporter
    state: restarted

- name: reload blackbox exporter
  service:
    name: blackbox_exporter
    state: reloaded
