---
- name: restart blackbox_exporter
  service:
    name: blackbox_exporter
    state: restarted

- name: reload blackbox_exporter
  service:
    name: blackbox_exporter
    state: reloaded

- name: reload systemd
  command: systemctl daemon-reload
